language: node_js
node_js:
  - '0.10'
  - '4'
  - '5'
  - '6'
  - '7'
before_install:
  - 'currentfolder=${PWD##*/}'
  - >-
    if [ "$currentfolder" != 'sailor-base' ]; then cd .. && eval "mv
    $currentfolder sailor-base" && cd sailor-base; fi
